#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1616424306                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The Moozpa! app lets you connect to a Zoom meeting and view when other participants raise their hands and have their audio unmuted. 

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Brenden Konnagan                                
your_link                                 : https://www.linkedin.com/in/brendenkonnagan                     
your_city                                 : Cincinnati                                
email_address                             : support@moozpa.app
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : brendenk1
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : View participants on Zoom during an in-person meeting
    description                           : The Moozpa! app lets you connect to a Zoom meeting and view when other participants raise their hands and have their audio unmuted.
    fontawesome_icon_name                 : hand-paper
    
  - title                                 : Connect easily to a Zoom meeting
    description                           : Ability to save and manage recurring or upcoming Zoom meeting details
    fontawesome_icon_name                 : bookmark

  - title                                 : Never manually enter your Zoom user name again
    description                           : Ability to use and manage a preferred user name when connecting to a Zoom meeting
    fontawesome_icon_name                 : save

  - title                                 : Split screen support
    description                           : On iPad, the ability to use in a split-screen environment
    fontawesome_icon_name                 : columns

  - title                                 : Native Mac support
    description                           : The ability to run on a Mac with an M series chip
    fontawesome_icon_name                 : desktop
    
  - title                                 : Stopwatch
    description                           : Integrated count-up timer for the presenter to keep track of time
    fontawesome_icon_name                 : clock
 



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               :                     # Replace with alternative image path or image URL.
cover_overlay_color                       : "#2F2C42"
cover_overlay_transparency                : 0.5

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#2F2C42"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#2F2C42"

feature_icons_foreground_color            : "#2F2C42"
feature_icons_background_color            : "#E6D4DB"

social_icons_foreground_color             : "#2F2C42"
social_icons_background_color             : "#CADAF5"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
